### ISSUE TITLE
Problem installing the template

### ISSUE THREAD

**Issue by graciborski** [crelies/TheComposableArchitecture-Xcode-Template#1]
Hi, I have an issue installing the template.
Running `swift install.swift` leaves me with `You don’t have permission` error (same running with sudo)
I've copied the `TheComposableArchitecture.xctemplate` directory to the `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Templates/Project Templates/iOS/Application` folder and I still cannot see a new template using `File > New > Project...` in Xcode. Am I doing something wrong? :)

**Comment by chris-swift-dev** [comment]
Hey @graciborski ,
this template is a file template, so you only see it when opening the new file wizard in Xcode.
I know that the name of the directory where it's placed suggests that this is a project template ;)
I have updated the README accordingly.

**Comment by chris-swift-dev** [comment]
@graciborski I have also updated the README with hints on how to fix the installation issues.
