### ISSUE TITLE
Update for TCA template to version 1.0?

### ISSUE THREAD

**Issue by ferencIOS** [crelies/TheComposableArchitecture-Xcode-Template#2]
Hi @crelies,

First off, thank you so much for your work! I've been using it and find it very valuable.

I wanted to inquire if you have plans to update the TCA template to version 1.0? I'm looking to utilize it in my upcoming project, and having an updated template would be fantastic.

Thank you in advance for your response and for all the hard work you've put into this.

Best regards!

**Comment by chris-swift-dev** [comment]
Hey @ferencIOS ,
I was busy in another world 😆 
Now I'm back and invested some time in improving and updating the template by taking the latest developments into account.
Checkout the branch [feature/1.7.x](https://github.com/crelies/TheComposableArchitecture-Xcode-Template/tree/feature/1.7.x) for a sneak preview.
I will create a new release tag soon.
